# base config
DESCRIPTION: Hematoma segmentation

SEED: 42

# Model
MODEL:
  NAME: resnet3d
  BACKBONE:
    NAME: res10
    IN_CHANNELS: 1
    LAYERS: [1, 1, 1, 1]
    STRIDES:
      - [2, 2, 1]
      - [2, 2, 1]
      - [2, 2, 1]
      - [2, 2, 2]
      - [2, 2, 2]
    INPLANE_RATIO: 1.0
  HEAD:
    OUT_CHANNELS: 2

# Optim
OPTIM:
  NAME: "adamw"
  LR: 3e-3
  WEIGHT_DECAY: 5e-4   # default is 5e-4
  ADAM_EPS: 1e-7       # fp32/amp 1e-7, fp16 1e-3
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5


TRAIN:
  PRINT_FREQ: 50
  GRADIENT_ACCUMULATION_STEPS: 1

TEST:
  EVALUATOR: "HematomaExpansionClassification"
  OTHER_METRICS: false
  SPLIT: "val"
  FINAL_MODEL: "best_val"   # last_step best_val
  PER_CLASS_RESULT: false


# Trainer
TRAINER:
  ALLCOMBINE:
    PREC: "fp32"

    USE_SEG_MASK: false

    METHOD: 1

