# base config
DESCRIPTION: Hematoma segmentation

SEED: 42

# Model
MODEL:
  NAME: dynunet
  KERNELS:
    - [3, 3, 3]
    - [3, 3, 3]
    - [3, 3, 3]
    - [3, 3, 3]
    - [3, 3, 3]
  STRIDES:
    - [2, 2, 1]
    - [2, 2, 1]
    - [2, 2, 1]
    - [2, 2, 2]
    - [2, 2, 2]
  FILTERS: [64, 96, 128, 192, 256, 384, 512, 768, 1024]
  IN_CHANNELS: 1
  OUT_CHANNELS: 3
  ACT: leakyrelu
  NORM: INSTANCE
  RES_BLOCK: FALSE
  DEEP_SUPERVISION: FALSE
  DEEP_SUPR_NUM: 3

# Optim
OPTIM:
  NAME: "adamw"
  LR: 3e-5
  WEIGHT_DECAY: 5e-4   # default is 5e-4
  ADAM_EPS: 1e-3
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5


TRAIN:
  PRINT_FREQ: 50
  GRADIENT_ACCUMULATION_STEPS: 1

TEST:
  EVALUATOR: "Segmentation"
  OTHER_METRICS: false
  SPLIT: "val"
  FINAL_MODEL: "last_step"   # last_step best_val
  PER_CLASS_RESULT: false


# Trainer
TRAINER:
  HEMATOMASEG:
    PREC: "fp32"

    SLIDING_WINDOW_INFER: true

